pragma solidity 0.8.9;
import "../src/BatchHarness.sol";
interface Vm {
 struct Log {bytes32[] topics;bytes data;address emitter;}
 function getCode(string calldata) external returns(bytes memory);function store(address,bytes32,bytes32) external;function load(address,bytes32) external view returns(bytes32);function addr(uint256) external returns(address);function sign(uint256,bytes32) external returns(uint8,bytes32,bytes32);function prank(address) external;function recordLogs() external;function getRecordedLogs() external returns(Log[] memory);
}
interface L {function transferFrom(address,address,uint256) external returns(bool);function sharesOf(address) external view returns(uint256);function allowance(address,address) external view returns(uint256);function nonces(address) external view returns(uint256);function DOMAIN_SEPARATOR() external view returns(bytes32);}
// Explicit external-domain fixture, not an EIP712StETH implementation theorem.
// Actual Lido permit nonce, signature validation and _approve are unmodified.
contract FixtureDomain {
 function domainSeparatorV4(address token) public view returns(bytes32){return keccak256(abi.encode(keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),keccak256("Liquid staked Ether 2.0"),keccak256("2"),block.chainid,token));}
 function hashTypedDataV4(address token,bytes32 h) external view returns(bytes32){return keccak256(abi.encodePacked(hex"1901",domainSeparatorV4(token),h));}
}
contract TransferFromTest {
 Vm constant vm=Vm(address(uint160(uint256(keccak256("hevm cheat code")))));
 bytes32 constant S=0x6038150aecaa250d524370a0fdcdec13f2690e0723eaf277f41d7cae26b359e6;
 bytes32 constant B=0x81a11fa1111afa59b50051f60ccf604a39d96acb484dc467ad8eadb4a63f0a5f;
 bytes32 constant ACTIVE=0x644132c4ddd5bb6f0655d5fe2870dcec7870e6be4758890f366b83441f9fdece;
 bytes32 constant DOMAIN=0x42b2d95e1ce15ce63bf9a8d9f6312cf44b23415c977ffa3b884333422af8941c;
 function deploy(string memory name,bytes memory args) internal returns(address t){bytes memory code=abi.encodePacked(vm.getCode(name),args);assembly{t:=create(0,add(code,32),mload(code))}require(t!=address(0));}
 function slot(address a) internal pure returns(bytes32){return keccak256(abi.encode(a,uint256(0)));}
 function allowanceSlot(address owner,address spender) internal pure returns(bytes32){return keccak256(abi.encode(spender,keccak256(abi.encode(owner,uint256(1)))));}
 function balance(L t,address a,uint256 n) internal {vm.store(address(t),slot(a),bytes32(n));}
 function allowance(L t,address owner,address spender,uint256 n) internal {vm.store(address(t),allowanceSlot(owner,spender),bytes32(n));}
 function fresh() internal returns(L t){t=L(deploy("artifacts/Lido.json",hex""));vm.store(address(t),S,bytes32(uint256(20)));vm.store(address(t),B,bytes32(uint256(2000)));vm.store(address(t),ACTIVE,bytes32(uint256(256)));balance(t,address(1),20);balance(t,address(99),5);allowance(t,address(1),address(this),1500);}
 function raw(L t,address spender,address owner,address to,uint256 amount) internal returns(bool,bytes memory){vm.prank(spender);return address(t).call(abi.encodeWithSelector(t.transferFrom.selector,owner,to,amount));}
 function err(L t,address spender,address owner,address to,uint256 amount,string memory reason) internal {(bool ok,bytes memory data)=raw(t,spender,owner,to,amount);require(!ok&&keccak256(data)==keccak256(abi.encodeWithSignature("Error(string)",reason)),reason);}
 function testFiniteAllowanceFirstAndExactTrueEvents() public {
  L t=fresh();vm.recordLogs();(bool ok,bytes memory ret)=raw(t,address(this),address(1),address(99),700);require(ok&&ret.length==32&&abi.decode(ret,(uint256))==1&&t.allowance(address(1),address(this))==800&&t.sharesOf(address(1))==13&&t.sharesOf(address(99))==12);
  Vm.Log[] memory logs=vm.getRecordedLogs();require(logs.length==3);
  require(logs[0].emitter==address(t)&&logs[0].topics[0]==keccak256("Approval(address,address,uint256)")&&logs[0].topics[1]==bytes32(uint256(1))&&logs[0].topics[2]==bytes32(uint256(uint160(address(this))))&&abi.decode(logs[0].data,(uint256))==800);
  require(logs[1].topics[0]==keccak256("Transfer(address,address,uint256)")&&abi.decode(logs[1].data,(uint256))==700&&logs[2].topics[0]==keccak256("TransferShares(address,address,uint256)")&&abi.decode(logs[2].data,(uint256))==7);
 }
 function testActualInfiniteAllowanceSkipsApprove() public {L t=fresh();allowance(t,address(1),address(this),type(uint256).max);vm.recordLogs();require(t.transferFrom(address(1),address(99),700)&&t.allowance(address(1),address(this))==type(uint256).max&&vm.getRecordedLogs().length==2);allowance(t,address(1),address(0),type(uint256).max);(bool ok,)=raw(t,address(0),address(1),address(99),100);require(ok);}
 function testSpendGuardPriorityBeforeConversion() public {L t=fresh();err(t,address(0),address(0),address(0),type(uint128).max,"ALLOWANCE_EXCEEDED");allowance(t,address(0),address(0),type(uint128).max);err(t,address(0),address(0),address(0),type(uint128).max,"APPROVE_FROM_ZERO_ADDR");allowance(t,address(1),address(0),type(uint128).max);err(t,address(0),address(1),address(0),type(uint128).max,"APPROVE_TO_ZERO_ADDR");allowance(t,address(0),address(0),type(uint256).max);err(t,address(0),address(0),address(0),type(uint128).max,"ETH_TOO_LARGE");err(t,address(0),address(0),address(0),0,"TRANSFER_FROM_ZERO_ADDR");}
 function testFiniteMaximumMinusOneNotInfinite() public {L t=fresh();allowance(t,address(1),address(this),type(uint256).max-1);err(t,address(this),address(1),address(99),type(uint256).max,"ALLOWANCE_EXCEEDED");}
 function testSpenderOwnerStillUsesAllowance() public {L t=fresh();err(t,address(1),address(1),address(99),100,"ALLOWANCE_EXCEEDED");allowance(t,address(1),address(1),100);(bool ok,)=raw(t,address(1),address(1),address(99),100);require(ok&&t.allowance(address(1),address(1))==0);}
 function testLatePauseAndOverflowRestoreAllowance() public {L t=fresh();vm.store(address(t),ACTIVE,bytes32(0));err(t,address(this),address(1),address(99),700,"CONTRACT_IS_STOPPED");require(t.allowance(address(1),address(this))==1500&&t.sharesOf(address(1))==20);vm.store(address(t),ACTIVE,bytes32(uint256(2)));balance(t,address(99),type(uint256).max);err(t,address(this),address(1),address(99),700,"MATH_ADD_OVERFLOW");require(t.allowance(address(1),address(this))==1500&&t.sharesOf(address(1))==20);}
 function testAliasFreshRecipientAndZeroFiniteApproval() public {L t=fresh();require(t.transferFrom(address(1),address(1),700)&&t.sharesOf(address(1))==20&&t.allowance(address(1),address(this))==800);vm.recordLogs();require(t.transferFrom(address(1),address(99),0)&&t.allowance(address(1),address(this))==800&&vm.getRecordedLogs().length==3);}
 function testNestedMappingNotSharesSlotOrReversedKeys() public {L t=fresh();allowance(t,address(1),address(this),0);allowance(t,address(this),address(1),700);balance(t,address(1),700);err(t,address(this),address(1),address(99),100,"ALLOWANCE_EXCEEDED");}
 function testFuzzAllowanceTokenUnitsAndAlias(uint64 n,uint64 extra,bool same,bool infinite) public {L t=fresh();uint256 amount=uint256(n)*100;uint256 limit=infinite?type(uint256).max:amount+uint256(extra);allowance(t,address(1),address(this),limit);balance(t,address(1),uint256(n)+9);address to=same?address(1):address(99);require(t.transferFrom(address(1),to,amount));require(t.allowance(address(1),address(this))==(infinite?limit:uint256(extra))&&t.sharesOf(address(1))==(same?uint256(n)+9:9));if(!same)require(t.sharesOf(address(99))==uint256(n)+5);}
 function setup() internal returns(L t,BatchHarness q,address user){t=fresh();address w=deploy("artifacts/WstETH.json",abi.encode(address(t)));q=new BatchHarness(IWstETH(w));q.seed(0,0,0,9);q.setResume(0);user=vm.addr(1);balance(t,user,20);balance(t,address(q),5);FixtureDomain d=new FixtureDomain();vm.store(address(t),DOMAIN,bytes32(uint256(uint160(address(d)))));}
 function xs() internal pure returns(uint256[] memory z){z=new uint256[](2);z[0]=700;z[1]=800;}
 function signed(L t,BatchHarness q,address user,uint256 value) internal returns(WithdrawalQueue.PermitInput memory p){p.value=value;p.deadline=type(uint256).max;bytes32 h=keccak256(abi.encode(keccak256("Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)"),user,address(q),p.value,t.nonces(user),p.deadline));(p.v,p.r,p.s)=vm.sign(1,keccak256(abi.encodePacked(hex"1901",t.DOMAIN_SEPARATOR(),h)));}
 function testActualDirectRequestBatch() public {(L t,BatchHarness q,address user)=setup();allowance(t,user,address(q),1500);vm.prank(user);uint256[] memory ids=q.requestWithdrawals(xs(),address(0));require(ids[0]==1&&ids[1]==2&&q.metadata(1).cumulativeStETH==700&&q.metadata(2).cumulativeStETH==1500&&q.metadata(2).cumulativeShares==15&&t.sharesOf(user)==5&&t.sharesOf(address(q))==20&&t.allowance(user,address(q))==0);}
 function testActualPermitThenDirectBatch() public {(L t,BatchHarness q,address user)=setup();WithdrawalQueue.PermitInput memory p=signed(t,q,user,1500);vm.prank(user);uint256[] memory ids=q.requestWithdrawalsWithPermit(xs(),address(0),p);require(ids[0]==1&&ids[1]==2&&t.nonces(user)==1&&t.allowance(user,address(q))==0&&t.sharesOf(user)==5&&q.metadata(2).cumulativeShares==15);}
 function testLateAllowanceFailureRestoresRealPermitAndFirstItem() public {(L t,BatchHarness q,address user)=setup();WithdrawalQueue.PermitInput memory p=signed(t,q,user,1400);vm.prank(user);(bool ok,bytes memory ret)=address(q).call(abi.encodeWithSelector(q.requestWithdrawalsWithPermit.selector,xs(),address(0),p));require(!ok&&keccak256(ret)==keccak256(abi.encodeWithSignature("Error(string)","ALLOWANCE_EXCEEDED")));require(t.nonces(user)==0&&t.allowance(user,address(q))==0&&q.getLastRequestId()==0&&t.sharesOf(user)==20&&t.sharesOf(address(q))==5);}
}
