import LidoSRv3.Audit.Verity.ConsolidationValueTx

/-!
# Consolidation value-interpreter correspondence

These theorems connect a successful run of the justified value-bearing
interpreter to the committed schedule produced by the pinned source model.
They do not invoke the official function denotation.
-/

namespace LidoSRv3.Audit.Spec.ConsolidationValueCorrespondence

open _root_.Verity
open LidoSRv3.Audit.SolidityConsolidation
open LidoSRv3.Audit.Verity.ConsolidationValueTx

theorem execute_committed_schedule (inputs : Inputs) (obs : Observables)
    (before : ContractState)
    (hSource : sourceRun inputs = .committed obs)
    (hFunds : inputs.msgValue.val ≤ before.selfBalance.val) :
    (execute inputs).run before =
      .success () (afterCalls obs.calls before) := by
  have hValue := committed_call_value_sum inputs obs hSource
  have hCallFunds : callValueSum obs.calls ≤ before.selfBalance.val := by
    rw [hValue]
    exact hFunds
  unfold execute
  rw [hSource]
  exact forwardCalls_run obs.calls before hCallFunds

/-- Any successful interpreter run is exactly the source-committed request
schedule.  The fresh journal is generated by `externalCallBindTo`, including
its targets, values, payload words, and order. -/
theorem execute_success_corresponds_to_committed_requests
    (inputs : Inputs) (before after : ContractState)
    (hFunds : inputs.msgValue.val ≤ before.selfBalance.val)
    (hExecute : (execute inputs).run before = .success () after) :
    ∃ obs,
      sourceRun inputs = .committed obs ∧
      after = afterCalls obs.calls before ∧
      freshCalls before after = obs.calls.map requestEntry ∧
      forwardedValue before after = inputs.msgValue.val ∧
      noConsensusLayerVerify before after := by
  cases hSource : sourceRun inputs with
  | reverted reason =>
      simp [execute, hSource, Contract.run] at hExecute
  | committed obs =>
      have hExpected :=
        execute_committed_schedule inputs obs before hSource hFunds
      rw [hExecute] at hExpected
      injection hExpected with hAfter
      subst after
      refine ⟨obs, rfl, rfl, afterCalls_fresh obs.calls before, ?_, ?_⟩
      · rw [afterCalls_forwardedValue,
          committed_call_value_sum inputs obs hSource]
      · exact afterCalls_noConsensusLayerVerify obs.calls before

end LidoSRv3.Audit.Spec.ConsolidationValueCorrespondence
