[profile.default]
src = "src"
test = "test"
optimizer = true
optimizer_runs = 200
evm_version = "byzantium"
remappings = ["contracts/=../../account-fee-distribution/solidity/vendor/contracts/", "@aragon/os/=../../account-fee-distribution/solidity/vendor/@aragon/os/", "openzeppelin-solidity/=../../account-fee-distribution/solidity/vendor/openzeppelin-solidity/"]
allow_paths = ["../../account-fee-distribution/solidity/vendor"]
