import LidoSRv3.Audit.Allocation
import LidoSRv3.Audit.StrategyProofs
import LidoSRv3.Audit.Common.Atomicity
import LidoSRv3.Audit.Common.Bounded
import LidoSRv3.Audit.Guarantees.PAlloc1
import LidoSRv3.Audit.Guarantees.PAlloc1Phase3
import LidoSRv3.Audit.Guarantees.PAlloc2
import LidoSRv3.Audit.Guarantees.PAlloc1EugeneBound
import LidoSRv3.Audit.Guarantees.PAccount1
import LidoSRv3.Audit.Verity.HandleOracleReportTx
import LidoSRv3.Tests.HandleOracleReportTxMutants
import LidoSRv3.Audit.Guarantees.PAddress1
import LidoSRv3.Audit.Verity.AddressAdmission
import LidoSRv3.Audit.Verity.ConsolidationCallFragment
import LidoSRv3.Audit.Guarantees.PConsolidation1
import LidoSRv3.Audit.Verity.ConsolidationTx
import LidoSRv3.Tests.ConsolidationTxMutants
import LidoSRv3.Audit.Guarantees.PDeposit1
import LidoSRv3.Audit.Guarantees.PConsolidationEth1
import LidoSRv3.Audit.Verity.PConsolidationEth1RefundTx
import LidoSRv3.Audit.Verity.PConsolidationEth1RequestTx
import LidoSRv3.Tests.PConsolidationEth1RefundTxMutants
import LidoSRv3.Tests.PConsolidationEth1RequestTxMutants
import LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants
import LidoSRv3.Audit.Guarantees.PSsz1
import LidoSRv3.Audit.Verity.SszEncodingTx
import LidoSRv3.Tests.SszEncodingTxMutants
import LidoSRv3.Audit.Source.GIndexConcatCorrespondence
import LidoSRv3.Audit.Guarantees.PTopup1
import LidoSRv3.Tests.TopupTxMutants
import LidoSRv3.Audit.Verity.TopupHybrid
import LidoSRv3.Tests.TopupHybridMutants
import LidoSRv3.Audit.Guarantees.PTopup2
import LidoSRv3.Audit.Verity.Topup2Tx
import LidoSRv3.Tests.Topup2TxMutants
import LidoSRv3.Audit.Guarantees.PReserve1
import LidoSRv3.Audit.Guarantees.PReserveRelational
import LidoSRv3.Audit.Guarantees.PReserveRelationalVerity
import LidoSRv3.Tests.ReserveRelationalTxMutants
import LidoSRv3.Tests.DepositTxMutants
import LidoSRv3.Tests.DepositParentTxMutants
import LidoSRv3.Tests.MinFirstAmountTxMutants
import LidoSRv3.Tests.MinFirstDistributionTxMutants
import LidoSRv3.Audit.Verity.AllocationTx
import LidoSRv3.Audit.Spec.AllocationCorrespondence
import LidoSRv3.Tests.PackAAllocSpecMutants
import LidoSRv3.Audit.Spec.EthJournalCorrespondence
import LidoSRv3.Tests.PackBEthJournalMutants
import LidoSRv3.Audit.Spec.SszCorrespondence
import LidoSRv3.Tests.PackCSszMutants
import LidoSRv3.Audit.Spec.AddressClaimCorrespondence
import LidoSRv3.Tests.PackDAddressClaimMutants
import LidoSRv3.Audit.Spec.OracleFrameCorrespondence
import LidoSRv3.Tests.PackEOracleFrameMutants
import LidoSRv3.Audit.Spec.ConsolidationObserveCorrespondence
import LidoSRv3.Tests.PackFConsolidationObserveMutants
import LidoSRv3.Audit.Provenance.Deposit
import LidoSRv3.Tests.PackGDepositProvenanceMutants
import LidoSRv3.Audit.Provenance.TopupBeacon
import LidoSRv3.Tests.PackGTopupProvenanceMutants
import LidoSRv3.Audit.Provenance.ConsolidationRequest
import LidoSRv3.Tests.PackGEth1ProvenanceMutants
import LidoSRv3.Audit.Spec.DepositEthJournalCorrespondence
import LidoSRv3.Tests.PackJDepositEthJournalMutants
import LidoSRv3.Audit.Spec.TopupEthJournalCorrespondence
import LidoSRv3.Tests.PackJTopupEthJournalMutants
import LidoSRv3.Audit.Spec.HashIdentificationChild
import LidoSRv3.Tests.PackS1HashMutants
import LidoSRv3.Audit.Spec.ConsolidationBridgeGap
import LidoSRv3.Tests.PackCGapMutants
import LidoSRv3.Audit.Spec.Eip4788AnchorChild
import LidoSRv3.Tests.PackW2Eip4788Mutants
import LidoSRv3.Audit.Spec.ProductionGindexChild
import LidoSRv3.Tests.PackW2GindexMutants
import LidoSRv3.Audit.Spec.ConsolidationDenoteCallsChild
import LidoSRv3.Tests.PackW2DenoteMutants
import LidoSRv3.Audit.Spec.AddressClaimBatchCorrespondence
import LidoSRv3.Tests.PackW2AddressBatchMutants
import LidoSRv3.Audit.Spec.Topup2WeiConversionChild
import LidoSRv3.Tests.PackW2Topup2WeiMutants
import LidoSRv3.Audit.Spec.ReserveQueueCacheChild
import LidoSRv3.Tests.PackW2ReserveMutants
import LidoSRv3.Audit.Spec.PauseAdmissionCorrespondence
import LidoSRv3.Audit.Spec.VaultHubScopeChild
import LidoSRv3.Audit.Spec.DerefSupplementalChild
import LidoSRv3.Tests.PackW2ScopeMutants
import LidoSRv3.Audit.Spec.AllocExecCorrespondence
import LidoSRv3.Audit.Guarantees.PAllocExec1
import LidoSRv3.Tests.PackN1AllocExecMutants
import LidoSRv3.Audit.Spec.EthJournalConfinement
import LidoSRv3.Audit.Guarantees.PEthJournal1
import LidoSRv3.Tests.PackN2EthJournalMutants
import LidoSRv3.Audit.Guarantees.PVaultEth1
import LidoSRv3.Tests.PackP2VaultEthMutants
import LidoSRv3.Audit.Spec.OracleMintCorrespondence
import LidoSRv3.Audit.Source.SubmitReportFeeCorrespondence
import LidoSRv3.Audit.Verity.SubmitReportEntryTx
import LidoSRv3.Audit.Guarantees.POracleSupply1
import LidoSRv3.Tests.PackN3OracleMintMutants
import LidoSRv3.Tests.PackP3SubmitReportEntryMutants
import LidoSRv3.Audit.Spec.AddressClaimFuelCorrespondence
import LidoSRv3.Audit.Guarantees.PAddressBatch1
import LidoSRv3.Tests.PackN4AddressBatchMutants
import LidoSRv3.Audit.Spec.SszLiveCorrespondence
import LidoSRv3.Audit.Guarantees.PSszLive1
import LidoSRv3.Tests.PackN5SszLiveMutants
import LidoSRv3.Audit.Spec.ConsolidationValueCorrespondence
import LidoSRv3.Audit.Verity.ConsolidationOfficialDenoteSuccess
import LidoSRv3.Audit.Guarantees.PConsolidationValue1
import LidoSRv3.Tests.PackN6ConsolValueMutants
import LidoSRv3.Tests.PackP6OfficialSuccessMutants
import LidoSRv3.Tests.AllocationTxMutants
import LidoSRv3.Tests.AddressSourceMutants
import LidoSRv3.Audit.Verity.Tests.SszTxSimulation

/-!
Machine-readable-in-build trust report for the first audit slice.

## Allowed axioms

Every theorem printed below may depend only on the three Lean foundational
axioms `propext`, `Classical.choice`, and `Quot.sound`.

`Classical.choice` is an **accepted** dependency, disclosed in
`audit/assumptions.yaml` as `A-CLASSICAL-CHOICE`: it is a standard Lean 4 /
Mathlib axiom discharged by the kernel, it makes the development classical
rather than constructive, and no project-specific claim rests on it.  It is
named here rather than folded silently into "Lean foundations" so that a
reviewer reading this report sees the same three-axiom boundary that the
assurance metadata records.

Anything outside those three is a proof escape and is *not* accepted.  In
particular `sorryAx`, `Lean.ofReduceBool`, and any project-introduced `axiom`
must not appear in the output below.  The single disclosed exception is the
canonical P-ALLOC-1 Phase-3 compilation theorems, which additionally report the
generated `consumed_summary_function_spec_compiles._native.native_decide.ax_1_1`
dependency recorded in the target manifest.

Subject to that one recorded exception, there are no undisclosed project-level
assumptions or proof escapes.
-/

#print axioms LidoSRv3.Audit.Quantity.checkedDiv_zero
#print axioms LidoSRv3.Audit.Quantity.saturatingSub_zero_of_le
#print axioms LidoSRv3.Audit.revert_restores_state_value_and_logs
#print axioms LidoSRv3.Audit.revert_may_retain_attempts
#print axioms LidoSRv3.Audit.valid_result_preserves_router_order
#print axioms LidoSRv3.Audit.Guarantees.PAlloc1.checked_execute
#print axioms LidoSRv3.Audit.Spec.AllocationCorrespondence.alloc1_spec_capacity_correspondence
#print axioms LidoSRv3.Audit.Spec.AllocationCorrespondence.alloc2_spec_step_amount_correspondence
#print axioms LidoSRv3.Audit.Spec.AllocationCorrespondence.topup2_per_key_remains_gwei
#print axioms LidoSRv3.Audit.Spec.AllocationCorrespondence.spec_amounts_do_not_imply_linkssource
#print axioms LidoSRv3.Tests.PackAAllocSpecMutants.target_as_capacity_kill_line_refutes_alloc1_spec
#print axioms LidoSRv3.Tests.PackAAllocSpecMutants.spec_amounts_kill_line_refutes_linkssource
#print axioms LidoSRv3.Audit.Spec.EthJournalCorrespondence.success_journal_projects_to_spec
#print axioms LidoSRv3.Tests.PackBEthJournalMutants.third_destination_other_kill_line_refutes_spec_journal
#print axioms LidoSRv3.Tests.PackBEthJournalMutants.third_destination_lido_kill_line_refutes_spec_journal
#print axioms LidoSRv3.Audit.Spec.SszCorrespondence.verifyProof_implies_gindex
#print axioms LidoSRv3.Audit.Spec.SszCorrespondence.gindex_concat_matches_spec
#print axioms LidoSRv3.Tests.PackCSszMutants.skip_gindex_kill_line_refutes_structural_child
#print axioms LidoSRv3.Tests.PackCSszMutants.engine_mutant_disagrees_with_sha256engine
#print axioms LidoSRv3.Audit.Spec.AddressClaimCorrespondence.two_claim_payouts_match_reads
#print axioms LidoSRv3.Tests.PackDAddressClaimMutants.swapped_payout_order_kill_line_refutes_batch
#print axioms LidoSRv3.Tests.PackDAddressClaimMutants.wrong_recipient_kill_line_refutes_batch
#print axioms LidoSRv3.Audit.Spec.OracleFrameCorrespondence.oracle_frame_shares_are_the_argument
#print axioms LidoSRv3.Audit.Spec.OracleFrameCorrespondence.account_parent_remains_order_only
#print axioms LidoSRv3.Audit.Spec.OracleFrameCorrespondence.eugene_bound_cited
#print axioms LidoSRv3.Tests.PackEOracleFrameMutants.computed_fee_kill_line_refutes_oracle_frame
#print axioms LidoSRv3.Audit.Spec.ConsolidationObserveCorrespondence.observe_success_payloads_reread_maps
#print axioms LidoSRv3.Audit.Spec.ConsolidationObserveCorrespondence.persist_payloads_reread
#print axioms LidoSRv3.Audit.Spec.ConsolidationObserveCorrespondence.gateway_nonzero_remains_named_hyp
#print axioms LidoSRv3.Tests.PackFConsolidationObserveMutants.swapped_map_reread_kill_line_refutes_observe
#print axioms LidoSRv3.Audit.Provenance.Deposit.canonical_deposit_contract_pin
#print axioms LidoSRv3.Audit.Provenance.Deposit.canonical_thirty_two_ether_pin
#print axioms LidoSRv3.Audit.Provenance.Deposit.production_conserving_config_at_thirty_two_ether
#print axioms LidoSRv3.Tests.PackGDepositProvenanceMutants.wrong_beacon_pin_kill_line
#print axioms LidoSRv3.Audit.Provenance.TopupBeacon.topup_verity_beacon_is_production_pin
#print axioms LidoSRv3.Audit.Provenance.TopupBeacon.topup_canonical_eq_deposit_canonical
#print axioms LidoSRv3.Tests.PackGTopupProvenanceMutants.dead_beacon_model_kill_line_disagrees_with_pin
#print axioms LidoSRv3.Audit.Provenance.ConsolidationRequest.ensemble_request_is_not_canonical
#print axioms LidoSRv3.Audit.Provenance.ConsolidationRequest.rewrite_maps_ensemble_to_canonical
#print axioms LidoSRv3.Tests.PackGEth1ProvenanceMutants.dead_rewrite_kill_line_refutes_canonical_rewrite
#print axioms LidoSRv3.Audit.Spec.DepositEthJournalCorrespondence.deposit_success_journal_projects_to_spec
#print axioms LidoSRv3.Tests.PackJDepositEthJournalMutants.third_destination_beacon_push_kill_line_refutes_projection_totality
#print axioms LidoSRv3.Audit.Spec.TopupEthJournalCorrespondence.topup_value_moving_journal_projects
#print axioms LidoSRv3.Audit.Spec.TopupEthJournalCorrespondence.topup_wrap_to_zero_journal_empty
#print axioms LidoSRv3.Tests.PackJTopupEthJournalMutants.beacon_as_consolidation_kill_line_refutes_dest_restriction
#print axioms LidoSRv3.Audit.Spec.HashIdentificationChild.hash_identification_agrees_on_bytes
#print axioms LidoSRv3.Tests.PackS1HashMutants.engine_mutant_still_disagrees
#print axioms LidoSRv3.Audit.Spec.ConsolidationBridgeGap.official_external_call_reverts
#print axioms LidoSRv3.Audit.Spec.ConsolidationBridgeGap.gateway_nonzero_remains_named_hyp
#print axioms LidoSRv3.Tests.PackCGapMutants.dropping_gateway_nonzero_admits_free_batch
#print axioms LidoSRv3.Audit.Spec.Eip4788AnchorChild.ageCheck_ok_of_le
#print axioms LidoSRv3.Tests.PackW2Eip4788Mutants.skip_age_bound_kill_line
#print axioms LidoSRv3.Audit.Spec.ProductionGindexChild.cl_validator_index_is_toy
#print axioms LidoSRv3.Tests.PackW2GindexMutants.claimed_cl_validator_index_ten_is_false
#print axioms LidoSRv3.Audit.Spec.ProductionGindexChild.production_gindex_binding
#print axioms LidoSRv3.Tests.PackW2GindexMutants.wrong_packed_word_is_not_production_binding
#print axioms LidoSRv3.Audit.Spec.ConsolidationDenoteCallsChild.requestOne_uses_widened_call_constructor
#print axioms LidoSRv3.Audit.Spec.ConsolidationDenoteCallsChild.official_raw_call_still_reverts
#print axioms LidoSRv3.Audit.Spec.ConsolidationDenoteCallsChild.preservesEthBalance_gap_remains
#print axioms LidoSRv3.Tests.PackW2DenoteMutants.official_revert_with_widened_bind
#print axioms LidoSRv3.Audit.Spec.AddressClaimBatchCorrespondence.three_claim_payouts_match_reads
#print axioms LidoSRv3.Audit.Spec.AddressClaimBatchCorrespondence.length_mismatch_reverts
#print axioms LidoSRv3.Tests.PackW2AddressBatchMutants.swapped_payout_order_kill_line_refutes_three_item_batch
#print axioms LidoSRv3.Audit.Spec.Topup2WeiConversionChild.aligned_five_gwei_budget
#print axioms LidoSRv3.Tests.PackW2Topup2WeiMutants.raw_valueWei_mutant_on_five_gwei_eq_five_billion_ne_five
#print axioms LidoSRv3.Audit.Spec.ReserveQueueCacheChild.fresh_queue_cache_is_equality
#print axioms LidoSRv3.Tests.PackW2ReserveMutants.fresh_queue_cache_not_universal
#print axioms LidoSRv3.Audit.Spec.PauseAdmissionCorrespondence.request_or_unwrap_pause_balance_is_permissionless
#print axioms LidoSRv3.Audit.Spec.VaultHubScopeChild.approved_destination_cases
#print axioms LidoSRv3.Audit.Spec.DerefSupplementalChild.deref_closure_exists_shape
#print axioms LidoSRv3.Tests.PackW2ScopeMutants.approved_destination_has_only_six_scoped_ctors
#print axioms LidoSRv3.Tests.PackW2ScopeMutants.packed_config_clobber_kill_line_refutes_parent
#print axioms LidoSRv3.Audit.Guarantees.PAllocExec1.router_produces_executes_allocation
#print axioms LidoSRv3.Audit.Guarantees.PAllocExec1.allocated_amount_times_deposit_size
#print axioms LidoSRv3.Tests.PackN1AllocExecMutants.raw_count_router_kill_line_refutes_parent
#print axioms LidoSRv3.Tests.PackN1AllocExecMutants.raw_count_as_wei_kill_line
#print axioms LidoSRv3.Audit.Guarantees.PEthJournal1.journal_approved_excludes_protocol_return_paths
#print axioms LidoSRv3.Audit.Guarantees.PEthJournal1.every_modeled_success_journal_approved
#print axioms LidoSRv3.Tests.PackN2EthJournalMutants.mutant_lido_approved_not_excluded_kill_line
#print axioms LidoSRv3.Tests.PackN2EthJournalMutants.fifth_destination_kill_line_retains_success_premises
#print axioms LidoSRv3.Audit.Guarantees.PVaultEth1.protocol_return_value_hops
#print axioms LidoSRv3.Audit.Guarantees.PVaultEth1.vault_to_lido_value_frame_inhabited
#print axioms LidoSRv3.Audit.Guarantees.PVaultEth1.vault_to_withdrawal_queue_value_frame_inhabited
#print axioms LidoSRv3.Tests.PackP2VaultEthMutants.zero_value_frame_kill_line_refutes_parent
#print axioms LidoSRv3.Tests.PackP2VaultEthMutants.mutant_vault_lido_as_lidoPull_refutes_projection
#print axioms LidoSRv3.Audit.Guarantees.POracleSupply1.oracle_supply_mint_and_cap
#print axioms LidoSRv3.Audit.Guarantees.POracleSupply1.oracle_supply_live_computed_mint
#print axioms LidoSRv3.Tests.PackN3OracleMintMutants.sum_balances_mutant_killed
#print axioms LidoSRv3.Tests.PackN3OracleMintMutants.raw_fee_mutant_killed
#print axioms LidoSRv3.Tests.PackN3OracleMintMutants.free_argument_does_not_satisfy_computed_observe
#print axioms LidoSRv3.Audit.Guarantees.POracleSupply1.oracle_supply_submit_report_data_computed_entry
#print axioms LidoSRv3.Audit.SolidityAccounting.SubmitReportEntry.entry_mint_le_pinned_shares
#print axioms LidoSRv3.Audit.SolidityAccounting.SubmitReportEntry.entry_mint_eq_pinned_of_exact
#print axioms LidoSRv3.Tests.PackP3SubmitReportEntryMutants.still_free_entry_kill_line_refutes_parent
#print axioms LidoSRv3.Tests.PackP3SubmitReportEntryMutants.skips_simulate_kill_line_refutes_parent
#print axioms LidoSRv3.Tests.PackP3SubmitReportEntryMutants.hash_premise_is_load_bearing
#print axioms LidoSRv3.Audit.Guarantees.PAddressBatch1.p_address_batch_1_fuel_bounded_live_claim_batch
#print axioms LidoSRv3.Audit.Guarantees.PAddressBatch1.p_address_batch_1_fuel_bounded_recipient_rename
#print axioms LidoSRv3.Tests.PackN4AddressBatchMutants.swapped_three_payout_order_kill_line_refutes_parent
#print axioms LidoSRv3.Tests.PackN4AddressBatchMutants.fixed_dest_rename_kill_line_refutes_parent
#print axioms LidoSRv3.Audit.Guarantees.PSszLive1.modeled_beacon_roots_live_ssz_consume
#print axioms LidoSRv3.Audit.Spec.Eip4788AnchorChild.eip4788_parent_root_identified
#print axioms LidoSRv3.Audit.Verity.BeaconRootsTx.spec_source_verity_beacon_roots
#print axioms LidoSRv3.Audit.Guarantees.PSszLive1.production_witness_admission_correspondence
#print axioms LidoSRv3.Tests.PackN5SszLiveMutants.skip_lookup_kill_line_refutes_parent
#print axioms LidoSRv3.Tests.PackN5SszLiveMutants.ignore_timestamp_kill_line_refutes_consume_parent
#print axioms LidoSRv3.Audit.Guarantees.PConsolidationValue1.official_denote_succeeds_and_justified_forwards_msg_value
#print axioms LidoSRv3.Audit.Guarantees.PConsolidationValue1.justified_interpreter_forwards_exactly_msg_value
#print axioms LidoSRv3.Audit.Verity.ConsolidationOfficialDenoteSuccess.official_denote_succeeds_on_value_bearing_request_calls
#print axioms LidoSRv3.Tests.PackN6ConsolValueMutants.official_denote_success_kill_line_refutes_parent
#print axioms LidoSRv3.Tests.PackN6ConsolValueMutants.zero_value_calls_refute_exact_forwarding
#print axioms LidoSRv3.Tests.PackP6OfficialSuccessMutants.official_denote_mutant_still_reverts_refutes_parent
#print axioms LidoSRv3.Tests.PackP6OfficialSuccessMutants.zero_value_link_mutant_refutes_value_bearing_conjunct
#print axioms LidoSRv3.Tests.PackP6OfficialSuccessMutants.rejecting_predeploy_refutes_unpremised_success
#print axioms LidoSRv3.Audit.Guarantees.PAlloc1.active_capacity_bounded
#print axioms LidoSRv3.Audit.Guarantees.PAlloc1.source_capacities_match_canonical
#print axioms LidoSRv3.Audit.Guarantees.PAlloc1.source_capacities_and_mapped_summary_transaction
#print axioms LidoSRv3.Audit.Guarantees.PAlloc1.verity_tx_simulates_allocation
#print axioms LidoSRv3.Audit.Guarantees.PAlloc1.verity_tx_revert_restores_snapshot
#print axioms LidoSRv3.Audit.Verity.AllocationTx.revert_restores_snapshot
#print axioms LidoSRv3.Audit.Guarantees.PAlloc1.router_order_preserved
#print axioms LidoSRv3.Audit.Guarantees.PAlloc1Phase3.mapped_summary_call_transaction
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.selects_least_open_bucket
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.verity_tx_simulates_min_first_distribution
#print axioms LidoSRv3.Audit.Verity.MinFirstDistributionTx.revert_restores_snapshot
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.source_selects_same_next_target
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.full_candidate_correspondence
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.source_amount_correspondence
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.source_pinned_expression_shape
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.source_amount_totality
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.proportional_step_correspondence_and_bounded
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.forall_proportional_step_correspondence_and_bounded
#print axioms LidoSRv3.Audit.Verity.MinFirstDistributionTx.allocateLoop_conserves_total
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.source_allocate_loop_conserves_requested
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.step_correspondence_and_full_loop_conservation
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.tx_step_matches_source
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.tx_step_is_safe
#print axioms LidoSRv3.Audit.Guarantees.PAlloc2.tx_revert_restores_snapshot
#print axioms LidoSRv3.Audit.Guarantees.PAlloc1EugeneBound.checked_amount_le_bond
#print axioms LidoSRv3.Audit.Guarantees.PAlloc1EugeneBound.operator_reward_share_le_configured_bond
#print axioms LidoSRv3.Audit.MinFirstAllocation.Model.success_conservation
#print axioms LidoSRv3.Audit.MinFirstAllocation.Model.success_capacity
#print axioms LidoSRv3.Audit.MinFirstAllocation.Model.failure_rolls_back
#print axioms LidoSRv3.Audit.MinFirstAllocation.Source.success_conservation
#print axioms LidoSRv3.Audit.MinFirstAllocation.Source.success_capacity
#print axioms LidoSRv3.Audit.MinFirstAllocation.Source.revert_rolls_back
#print axioms LidoSRv3.Audit.Guarantees.PAccount1.source_report_before_reward
#print axioms LidoSRv3.Audit.Guarantees.PAccount1.verity_tx_simulates_oracle_report
#print axioms LidoSRv3.Audit.Guarantees.PAccount1.verity_tx_revert_restores_snapshot
#print axioms LidoSRv3.Audit.Guarantees.PAccount1.mint_after_read_discipline
#print axioms LidoSRv3.Audit.Guarantees.PAccount1.mint_order_kill_line
#print axioms LidoSRv3.Audit.Verity.HandleOracleReportTx.verity_tx_simulates_pinned_source
#print axioms LidoSRv3.Audit.Verity.HandleOracleReportTx.revert_restores_snapshot
#print axioms LidoSRv3.Audit.Verity.HandleOracleReportTx.mintAfterReadDiscipline_holds
#print axioms LidoSRv3.Audit.Verity.HandleOracleReportTx.mintOrderKillLine_holds
#print axioms LidoSRv3.Tests.HandleOracleReportTxMutants.reordered_mint_read_kill_line_refutes_parent
#print axioms LidoSRv3.Audit.Verity.AddressAdmission.run_claim_success
#print axioms LidoSRv3.Audit.Verity.AddressAdmission.admission_address_equivariant
#print axioms LidoSRv3.Audit.Verity.AddressAdmission.claim_admits
#print axioms LidoSRv3.Audit.Verity.AddressAdmission.claim_rejects_empty_balance
#print axioms LidoSRv3.Audit.Verity.AddressAdmission.claim_rejects_when_paused
#print axioms LidoSRv3.Audit.Verity.AddressAdmission.ownerGated_not_admission_equivariant
#print axioms LidoSRv3.Audit.Verity.ConsolidationCallFragment.raw_call_entrypoint_always_reverts
#print axioms
  LidoSRv3.Audit.Verity.ConsolidationCallFragment.external_call_bind_entrypoint_always_reverts
#print axioms LidoSRv3.Audit.Verity.ConsolidationCallFragment.requestConsolidationBind_registered
#print axioms
  LidoSRv3.Audit.Verity.ConsolidationCallFragment.registered_external_call_bind_entrypoint_always_reverts
#print axioms LidoSRv3.Audit.Verity.ConsolidationCallFragment.guards_only_succeeds
#print axioms LidoSRv3.Audit.Verity.ConsolidationCallFragment.success_hypotheses_are_vacuous
#print axioms LidoSRv3.Audit.Guarantees.PAddress1.universal_address_writer_equivariance
#print axioms LidoSRv3.Audit.Guarantees.PAddress1.abstract_source_verity_tx_address_equivariance
#print axioms LidoSRv3.Audit.Verity.AddressTx.pinned_source_observable_correspondence
#print axioms LidoSRv3.Audit.Verity.AddressTx.executed_address_writes_follow_renamed_source
#print axioms LidoSRv3.Audit.Verity.AddressTx.every_revert_restores_snapshot
#print axioms LidoSRv3.Tests.AddressSourceMutants.verity_wrong_recipient_mutant_rejected
#print axioms LidoSRv3.Tests.AddressSourceMutants.verity_fixed_owner_writer_mutant_rejected
#print axioms LidoSRv3.Tests.AddressSourceMutants.verity_zero_amount_rejected
#print axioms LidoSRv3.Tests.AddressSourceMutants.fixed_owner_gate_not_admission_equivariant
#print axioms LidoSRv3.Tests.AddressSourceMutants.fixed_owner_gate_kill_line_refutes_parent
#print axioms LidoSRv3.Tests.AddressSourceMutants.fixed_owner_writer_kill_line_refutes_parent
#print axioms
  LidoSRv3.Audit.Guarantees.PConsolidation1.source_consolidation_preserves_eligibility_value_atomicity
#print axioms
  LidoSRv3.Audit.Guarantees.PConsolidation1.verity_tx_simulates_consolidation
#print axioms
  LidoSRv3.Audit.Guarantees.PConsolidation1.verity_tx_revert_restores_snapshot
#print axioms LidoSRv3.Audit.Verity.ConsolidationTx.function_spec_bridge_constructors
#print axioms LidoSRv3.Audit.Guarantees.PAddress1.bounded_transfer_model_source_tx
#print axioms LidoSRv3.Audit.Guarantees.PAddress1.bounded_live_claim_batch_storage_call_surface
#print axioms LidoSRv3.Audit.Verity.AddressClaimBatchTx.two_claim_batch_observe
#print axioms LidoSRv3.Audit.Verity.AddressClaimBatchTx.every_revert_restores_snapshot
#print axioms LidoSRv3.Audit.Verity.AddressTransferTx.tx_refines_source_witness
#print axioms LidoSRv3.Audit.Source.AddressTransferCorrespondence.fixed_caller_mutant_rejected
#print axioms LidoSRv3.Audit.Guarantees.PDeposit1.source_deposit_conserves_and_rolls_back
#print axioms LidoSRv3.Audit.Guarantees.PDeposit1.source_router_balance_unchanged
#print axioms LidoSRv3.Audit.Guarantees.PDeposit1.source_reverting_branch_moves_no_ether
#print axioms LidoSRv3.Audit.Guarantees.PDeposit1.source_nonconserving_deployment_reverts
#print axioms LidoSRv3.Audit.Guarantees.PDeposit1.verity_tx_revert_restores_snapshot
#print axioms LidoSRv3.Audit.Verity.DepositTx.run_simulates_source
#print axioms LidoSRv3.Tests.DepositTxMutants.double_beacon_send_rejected
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.verity_tx_composes_deposit_conservation_and_rollback
#print axioms LidoSRv3.Audit.Guarantees.PDeposit1.canonical_composition_witness
#print axioms LidoSRv3.Audit.Guarantees.PDeposit1.linked_deployment_push_is_word_bounded
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.linked_conserving_deployment_pull_is_word_bounded
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.linked_hypotheses_do_not_bound_the_line_972_product
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.skewed_pull_witness_turned_away_before_line_972
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.line_972_product_le_module_allocation
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.encodable_allocation_bounds_line_972_product
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.in_range_commit_is_word_bounded
#print axioms LidoSRv3.Audit.Guarantees.PDeposit1.oversized_run_commits
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.oversized_input_is_outside_the_source_domain
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.oversized_input_exceeds_word
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.abstract_parent_covers_inputs_the_verity_plane_omits
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.manyKey_input_is_within_the_source_domain
#print axioms LidoSRv3.Audit.Guarantees.PDeposit1.manyKey_run_commits
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.manyKey_links_source_two_legs
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.manyKey_entry_state_guards_are_load_bearing
#print axioms
  LidoSRv3.Audit.Guarantees.PDeposit1.manyKey_underfunded_entry_reverts_at_not_enough_ether
#print axioms LidoSRv3.Audit.Verity.DepositParentTx.execute_observes_source
#print axioms
  LidoSRv3.Audit.Verity.DepositParentTx.revert_after_intermediate_writes_restores_snapshot
#print axioms LidoSRv3.Audit.Verity.DepositParentTx.revert_observes_idle
#print axioms LidoSRv3.Tests.DepositParentTxMutants.mutant_none_reproduces_execute
#print axioms LidoSRv3.Tests.DepositParentTxMutants.skipped_allocation_write_rejected
#print axioms LidoSRv3.Tests.DepositParentTxMutants.skipped_dynamic_data_write_rejected
#print axioms LidoSRv3.Tests.DepositParentTxMutants.skipped_root_write_rejected
#print axioms LidoSRv3.Tests.DepositParentTxMutants.misrouted_push_rejected
#print axioms LidoSRv3.Tests.DepositParentTxMutants.dropped_push_rejected
#print axioms LidoSRv3.Tests.DepositParentTxMutants.root_failure_observes_idle
#print axioms LidoSRv3.Audit.Guarantees.PConsolidationEth1.eth_flow_confined
#print axioms LidoSRv3.Audit.Guarantees.PConsolidationEth1.consolidation_fee_path_confined
#print axioms LidoSRv3.Audit.Guarantees.PConsolidationEth1.eth_flow_parent
#print axioms LidoSRv3.Audit.Guarantees.PConsolidationEth1.eth_flow_parent_at_canonical
#print axioms LidoSRv3.Audit.Guarantees.PConsolidationEth1.verity_tx_universal_success_shape
#print axioms LidoSRv3.Audit.Guarantees.PConsolidationEth1.verity_tx_universal_revert_partition
#print axioms LidoSRv3.Audit.Guarantees.PConsolidationEth1.verity_tx_universal_zero_remainder_boundary
#print axioms LidoSRv3.Audit.Guarantees.PConsolidationEth1.verity_tx_success_and_revert_partition
#print axioms LidoSRv3.Audit.Guarantees.PConsolidationEth1.verity_tx_composes_value_flow_and_rollback
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.rejects_dropped_refund_leg
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.rejects_misrouted_vault_leg
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.rejects_corrupted_refund_amount
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.rejects_preserved_prefix_after_failed_hop
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.rejects_single_request_for_two_request_batch
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.universal_parent_is_predicate_at_honest
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.dropped_refund_leg_kill_line_refutes_universal_parent
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.misrouted_vault_kill_line_refutes_universal_parent
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.corrupted_refund_kill_line_refutes_universal_parent
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.single_request_kill_line_refutes_universal_parent
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.zero_value_kill_line_refutes_dropped_positivity
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.underfunded_kill_line_refutes_dropped_funding
#print axioms LidoSRv3.Tests.PConsolidationEth1CompositionTxMutants.fuel_exhaustion_kill_line_refutes_dropped_fuel_premise
#print axioms LidoSRv3.Audit.Verity.PConsolidationEth1RefundTx.gateway_refund_success_moves_value
#print axioms LidoSRv3.Audit.Verity.PConsolidationEth1RefundTx.gateway_refund_failure_keeps_prefix_out
#print axioms LidoSRv3.Audit.Verity.PConsolidationEth1RefundTx.withdraw_success_moves_to_lido
#print axioms LidoSRv3.Audit.Verity.PConsolidationEth1RefundTx.refund_failure_restores_snapshot
#print axioms LidoSRv3.Audit.Verity.PConsolidationEth1RequestTx.bus_forward_success
#print axioms LidoSRv3.Audit.Verity.PConsolidationEth1RequestTx.consolidation_fee_target_success
#print axioms LidoSRv3.Audit.Verity.PConsolidationEth1RequestTx.withdrawal_fee_success
#print axioms LidoSRv3.Audit.Verity.PConsolidationEth1RequestTx.consolidation_second_failure_discards_prefix
#print axioms LidoSRv3.Audit.Verity.PConsolidationEth1RequestTx.bus_failure_restores_snapshot
#print axioms LidoSRv3.Audit.Verity.PConsolidationEth1RefundTx.sourceGateway_committed_splits_to_vault_and_refund
#print axioms LidoSRv3.Tests.PConsolidationEth1RefundTxMutants.refund_misroute_kill_line
#print axioms LidoSRv3.Tests.PConsolidationEth1RefundTxMutants.double_refund_rejected
#print axioms LidoSRv3.Tests.PConsolidationEth1RefundTxMutants.leak_on_refund_failure_rejected
#print axioms LidoSRv3.Tests.PConsolidationEth1RequestTxMutants.keep_first_consolidation_fee_rejected
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.source_wrap_precludes_value_moving_commit
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.source_module_guard_required
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.source_wc_type2_guard_required
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.source_topup_conserves_and_rolls_back
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.source_router_balance_unchanged
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.source_reverting_branch_moves_no_ether
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.source_balance_guards_discharged
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.source_unchecked_accumulation_faithful
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.source_pinned_config_discharges_pubkey_guard
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.verity_tx_simulates_source
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.verity_wrap_to_zero_is_empty_commit
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.verity_nonzero_wrap_witness_reverts_and_restores
#print axioms LidoSRv3.Audit.Guarantees.PTopup1.verity_nonzero_wrap_reverts_and_restores
#print axioms
  LidoSRv3.Audit.Guarantees.PTopup1.verity_tx_simulates_source_with_nonzero_wrap_close
#print axioms LidoSRv3.Audit.Verity.TopupHybrid.verity_tx_simulates_source
#print axioms LidoSRv3.Tests.TopupHybridMutants.hybrid_simulation_covers_nonzero_wrap
#print axioms LidoSRv3.Tests.TopupHybridMutants.hybrid_simulation_covers_wrap_to_zero
#print axioms LidoSRv3.Tests.TopupTxMutants.mutant_none_reproduces_execute
#print axioms LidoSRv3.Tests.TopupTxMutants.honest_run_matches_source
#print axioms LidoSRv3.Tests.TopupTxMutants.skipped_allocation_write_rejected
#print axioms LidoSRv3.Tests.TopupTxMutants.dropped_push_rejected
#print axioms LidoSRv3.Tests.TopupTxMutants.misrouted_push_rejected
#print axioms LidoSRv3.Tests.TopupTxMutants.corrupted_amount_rejected
#print axioms LidoSRv3.Tests.TopupTxMutants.swapped_order_rejected
#print axioms LidoSRv3.Tests.TopupTxMutants.duplicated_push_rejected
#print axioms LidoSRv3.Tests.TopupTxMutants.allocation_write_failure_rolls_back
#print axioms LidoSRv3.Tests.TopupTxMutants.lido_pull_failure_rolls_back
#print axioms LidoSRv3.Tests.TopupTxMutants.first_beacon_failure_rolls_back
#print axioms LidoSRv3.Tests.TopupTxMutants.guard_discharge_at_wrapping_input
#print axioms LidoSRv3.Tests.TopupTxMutants.wrap_to_zero_commits_no_topup
#print axioms LidoSRv3.Tests.TopupTxMutants.guard_discharge_at_unregistered_module_input
#print axioms LidoSRv3.Tests.TopupTxMutants.guard_discharge_at_non_type2_wc_input
#print axioms LidoSRv3.Tests.TopupTxMutants.mutantRunNoAssert_eq_run_of_assert_passing
#print axioms LidoSRv3.Tests.TopupTxMutants.mutantRunNoAssert_commits_where_assert_fires
#print axioms LidoSRv3.Tests.TopupTxMutants.dropped_conservation_assert_kill_line_refutes_parent
#print axioms LidoSRv3.Tests.TopupTxMutants.dropped_module_guard_kill_line_refutes_parent
#print axioms LidoSRv3.Tests.TopupTxMutants.dropped_wc_guard_kill_line_refutes_parent
#print axioms LidoSRv3.Tests.TopupTxMutants.unwrapped_accumulator_kill_line_refutes_parent
#print axioms LidoSRv3.Audit.Source.Topup2.source_aggregate_bounded_by_block_cap
#print axioms LidoSRv3.Audit.Guarantees.PTopup2.aggregate_bounded_by_block_cap
#print axioms LidoSRv3.Audit.Guarantees.PTopup2.per_key_bounded_by_candidate
#print axioms LidoSRv3.Audit.Verity.Topup2Tx.tx_aggregate_bounded_by_block_cap
#print axioms LidoSRv3.Audit.Verity.Topup2Tx.tx_all_success_value_exact
#print axioms LidoSRv3.Audit.Verity.Topup2Tx.tx_revert_restores_world
#print axioms LidoSRv3.Audit.Verity.Topup2Tx.tx_committed_world_is_commit_fold
#print axioms LidoSRv3.Tests.Topup2TxMutants.over_cap_aggregate_rejected
#print axioms LidoSRv3.Tests.Topup2TxMutants.double_send_rejected
#print axioms LidoSRv3.Tests.Topup2TxMutants.reverting_adversary_cannot_leak_state
#print axioms LidoSRv3.Audit.Guarantees.PReserve1.source_spend_preserves_withdrawal_reserve
#print axioms LidoSRv3.Audit.Guarantees.PReserve1.verity_tx_simulates_reserve_spec
#print axioms LidoSRv3.Audit.Guarantees.PReserve1.verity_tx_preserves_withdrawal_reserve
#print axioms LidoSRv3.Audit.Guarantees.PReserveRelational.abstract_reserve_does_not_change_finalization
#print axioms LidoSRv3.Audit.Guarantees.PReserveRelational.source_reserve_does_not_change_finalization
#print axioms LidoSRv3.Audit.Guarantees.PReserveRelational.verity_tx_simulates_reserve_relational_spec
#print axioms LidoSRv3.Audit.Guarantees.PReserveRelational.verity_tx_reverts_on_locked_overflow
#print axioms LidoSRv3.Audit.Guarantees.PReserveRelational.verity_reserve_slot_is_not_read
#print axioms LidoSRv3.Audit.Guarantees.PReserveRelational.verity_reserve_does_not_change_finalization
#print axioms LidoSRv3.Audit.Guarantees.PReserveRelational.verity_revert_restores_snapshot
#print axioms LidoSRv3.Audit.Guarantees.PSsz1.deposit_root_iff
#print axioms LidoSRv3.Audit.Guarantees.PSsz1.deposit_unique_of_perfect
#print axioms LidoSRv3.Audit.Guarantees.PSsz1.sourceNode_mutant_kill_line_refutes_parent
#print axioms LidoSRv3.Audit.Guarantees.PSsz1.composed_ssz_encoding
#print axioms LidoSRv3.Audit.Guarantees.PSsz1.swapped_combine_kill_line_refutes_parent
#print axioms LidoSRv3.Audit.Guarantees.PSsz1.composedEncodingOkFull_not_trivial_crossed_witness
#print axioms LidoSRv3.Audit.Guarantees.PSsz1.inconsistent_witness_kill_line
#print axioms LidoSRv3.Audit.Guarantees.PSsz1.inconsistent_operation_index_kill_line
#print axioms LidoSRv3.Audit.Guarantees.PSsz1.sourceWitness_binds_sourceNode
#print axioms LidoSRv3.Audit.Guarantees.PSsz1.verity_tx_simulates_ssz_encoding
#print axioms LidoSRv3.Audit.Guarantees.PSsz1.verity_tx_two_batch_rolls_back
#print axioms LidoSRv3.Audit.Verity.SszEncodingTx.verity_tx_simulates_pinned_source
#print axioms LidoSRv3.Audit.Verity.SszEncodingTx.encoding_commits_structural_witness
#print axioms LidoSRv3.Audit.Verity.SszEncodingTx.revert_restores_snapshot
#print axioms LidoSRv3.Audit.Source.GIndexConcatCorrespondence.source_concat_matches_spec
#print axioms LidoSRv3.Audit.Source.GIndexConcatCorrespondence.source_concat_value_of_fits
#print axioms LidoSRv3.Audit.Source.GIndexConcatCorrespondence.source_concat_depth_overflow
#print axioms LidoSRv3.Audit.Verity.SszTxSimulation.ssz_tx_simulation_correct
#print axioms LidoSRv3.Audit.Verity.SszTxSimulation.sha256_call_world_rollback
#print axioms LidoSRv3.Audit.Verity.SszTxSimulation.root_mutant_rejected
#print axioms
  LidoSRv3.Audit.Source.DepositDataRootCorrespondence.source_pinned_config_discharges_deposit_data_root
#print axioms LidoSRv3.Audit.MinFirst.candidate_mem
#print axioms LidoSRv3.Audit.MinFirst.candidate_open
#print axioms LidoSRv3.Audit.MinFirst.candidate_none_no_open
#print axioms LidoSRv3.Audit.MinFirst.candidate_minimal
#print axioms LidoSRv3.Audit.MinFirst.candidate_router_tie
#print axioms LidoSRv3.Audit.MinFirst.incrementSelected_moduleId
#print axioms LidoSRv3.Audit.MinFirst.incrementSelected_active
#print axioms LidoSRv3.Audit.MinFirst.incrementSelected_monotone
#print axioms LidoSRv3.Audit.MinFirst.incrementSelected_eq_of_ne
#print axioms LidoSRv3.Audit.MinFirst.step_preserves_length
#print axioms LidoSRv3.Audit.MinFirst.step_preserves_module_order
#print axioms LidoSRv3.Audit.MinFirst.loop_preserves_length
#print axioms LidoSRv3.Audit.MinFirst.loop_preserves_module_order
#print axioms LidoSRv3.Audit.MinFirst.allocate_preserves_length
#print axioms LidoSRv3.Audit.MinFirst.allocate_preserves_module_order
#print axioms LidoSRv3.Audit.MinFirst.run_spent_le
#print axioms LidoSRv3.Audit.MinFirst.totalAllocated_le_requested
#print axioms LidoSRv3.Audit.Common.BoundedAmount.checkedAdd_sound
#print axioms LidoSRv3.Audit.Common.revert_rolls_back_state_and_committed_effects
#print axioms LidoSRv3.Audit.Common.success_exposes_exact_committed_effects
