#!/usr/bin/env python3
"""Generate exact Solidity constants from the actual Lean exporter output."""
import json
from pathlib import Path
root=Path(__file__).resolve().parent
vectors=json.loads((root/'vectors.json').read_text())
assert len(vectors)==64 and [x['seed'] for x in vectors]==list(range(64))
lines=['// SPDX-License-Identifier: MIT','pragma solidity 0.8.25;',
 '// Generated by build_vectors.py from actual Lean ModuleCall encoders.',
 'library DepositModuleVectors {',
 'function get(uint256 n) internal pure returns(bytes memory,bytes memory) {']
for row in vectors:
    lines.append('if(n==%d) return(hex"%s",hex"%s");'%(row['seed'],row['payload'],row['reply']))
lines+=['revert("vector out of bounds");','}','}']
(root/'solidity/DepositModuleVectors.sol').write_text('\n'.join(lines)+'\n')
