pragma solidity 0.8.9;
import "../src/BatchHarness.sol";
interface Vm {function getCode(string calldata) external returns(bytes memory);function store(address,bytes32,bytes32) external;function addr(uint256) external returns(address);function sign(uint256,bytes32) external returns(uint8,bytes32,bytes32);function prank(address) external;}
interface L {function getSharesByPooledEth(uint256) external view returns(uint256);function configure(address,address,bool) external;function moves() external view returns(uint256);function permitWrites() external view returns(uint256);}
interface W {function DOMAIN_SEPARATOR() external view returns(bytes32);function nonces(address) external view returns(uint256);function balanceOf(address) external view returns(uint256);function totalSupply() external view returns(uint256);function allowance(address,address) external view returns(uint256);}
contract QuoteTest {
 Vm constant vm=Vm(address(uint160(uint256(keccak256("hevm cheat code")))));
 bytes32 constant S=0x6038150aecaa250d524370a0fdcdec13f2690e0723eaf277f41d7cae26b359e6;
 bytes32 constant B=0x81a11fa1111afa59b50051f60ccf604a39d96acb484dc467ad8eadb4a63f0a5f;
 bytes32 constant C=0x096e465397f38e659238ccd5d5a2c434ced54a63fd8d694045bfb058ab9d8112;
 function deploy(string memory name,bytes memory args) internal returns(address target){bytes memory code=abi.encodePacked(vm.getCode(name),args);assembly{target:=create(0,add(code,32),mload(code))}require(target!=address(0));}
 function seed(address t,uint256 s,uint256 b,uint256 c) internal {vm.store(t,S,bytes32(s));vm.store(t,B,bytes32(b));vm.store(t,C,bytes32(c));}
 function raw(L t,uint256 a) internal returns(bool,bytes memory){return address(t).call(abi.encodeWithSelector(t.getSharesByPooledEth.selector,a));}
 function testPinnedKeccakSlots() public pure {require(S==keccak256("lido.StETH.totalAndExternalShares"));require(B==keccak256("lido.Lido.bufferedEtherAndDepositedPostReport"));require(C==keccak256("lido.Lido.clValidatorsBalanceAndClPendingBalance"));}
 function testActualLidoFormulaPackedWords() public {L t=L(deploy("artifacts/Lido.json",hex""));seed(address(t),100|(uint256(20)<<128),100|(uint256(200)<<128),300|(uint256(400)<<128));require(t.getSharesByPooledEth(100)==8);}
 function testStrictMaximumErrorBeforeZero() public {L t=L(deploy("artifacts/Lido.json",hex""));(bool ok,bytes memory ret)=raw(t,type(uint128).max);require(!ok&&keccak256(ret)==keccak256(abi.encodeWithSignature("Error(string)","ETH_TOO_LARGE")));seed(address(t),1,1,0);require(t.getSharesByPooledEth(uint256(type(uint128).max)-1)==uint256(type(uint128).max)-1);}
 function testZeroInternalEtherInvalidEmpty() public {L t=L(deploy("artifacts/Lido.json",hex""));(bool ok,bytes memory ret)=raw(t,0);require(!ok&&ret.length==0);}
 function testZeroSharesReturnsZero() public {L t=L(deploy("artifacts/Lido.json",hex""));seed(address(t),0,1,0);require(t.getSharesByPooledEth(100)==0);}
 function testRawUnderflowAndMultiplyOverflow() public {L t=L(deploy("artifacts/Lido.json",hex""));seed(address(t),uint256(1)<<128,1,0);require(t.getSharesByPooledEth(2)==type(uint256).max-1);}
 function testAllPackedFieldsMaximum() public {L t=L(deploy("artifacts/Lido.json",hex""));seed(address(t),100,type(uint256).max,type(uint256).max);require(t.getSharesByPooledEth(100)==0);}
 function testFuzzActualFullLido(uint128 total,uint128 externalShares,uint128 b,uint128 d,uint128 v,uint128 p,uint128 amount) public {L t=L(deploy("artifacts/Lido.json",hex""));seed(address(t),uint256(total)|(uint256(externalShares)<<128),uint256(b)|(uint256(d)<<128),uint256(v)|(uint256(p)<<128));uint256 a=uint256(amount)%uint256(type(uint128).max);uint256 i=uint256(b)+d+v+p;if(i==0){(bool ok,bytes memory ret)=raw(t,a);require(!ok&&ret.length==0);}else{uint256 expected;unchecked{expected=(a*(uint256(total)-externalShares))/i;}require(t.getSharesByPooledEth(a)==expected);}}
 function setup(address user,bool zeroSecond) internal returns(BatchHarness q,W w,L t){t=L(deploy("artifacts/QuoteHarness.json",hex""));w=W(deploy("artifacts/WstETH.json",abi.encode(address(t))));q=new BatchHarness(IWstETH(address(w)));q.seed(0,0,0,9);q.setResume(0);t.configure(address(q),address(w),zeroSecond);seed(address(t),15,1500,0);vm.store(address(w),keccak256(abi.encode(user,uint256(0))),bytes32(uint256(15)));vm.store(address(w),bytes32(uint256(2)),bytes32(uint256(15)));}
 function xs(uint256 a,uint256 b) internal pure returns(uint256[] memory z){z=new uint256[](2);z[0]=a;z[1]=b;}
 function permit() internal pure returns(WithdrawalQueue.PermitInput memory){return WithdrawalQueue.PermitInput(15,500,27,0,0);}
 function signed(BatchHarness q,W w,address user) internal returns(WithdrawalQueue.PermitInput memory p){p.value=15;p.deadline=type(uint256).max;bytes32 h=keccak256(abi.encode(keccak256("Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)"),user,address(q),15,w.nonces(user),p.deadline));(p.v,p.r,p.s)=vm.sign(1,keccak256(abi.encodePacked(hex"1901",w.DOMAIN_SEPARATOR(),h)));}
 function testStPermitConsumesPostCallbackPhysicalQuotes() public {(BatchHarness q,,L t)=setup(address(this),false);uint256[] memory ids=q.requestWithdrawalsWithPermit(xs(600,1200),address(0),permit());require(ids.length==2&&ids[0]==1&&ids[1]==2&&q.metadata(1).cumulativeShares==3&&q.metadata(2).cumulativeShares==6&&t.permitWrites()==1&&t.moves()==2);}
 function testActualQueueCastsOversizedPhysicalQuote() public {(BatchHarness q,,L t)=setup(address(this),false);vm.store(address(t),S,bytes32(uint256(1)<<128));uint256[] memory z=new uint256[](1);z[0]=600;uint256[] memory ids=q.requestWithdrawalsWithPermit(z,address(0),permit());uint256 expected;unchecked{expected=(uint256(600)*type(uint256).max)/3000;}require(expected>type(uint128).max&&ids[0]==1&&q.metadata(1).cumulativeShares==uint128(expected));}
 function testStLateQuoteInvalidRestoresPermitAndEarlierItem() public {(BatchHarness q,,L t)=setup(address(this),true);(bool ok,bytes memory ret)=address(q).call(abi.encodeWithSelector(q.requestWithdrawalsWithPermit.selector,xs(600,1200),address(0),permit()));require(!ok&&ret.length==0&&q.getLastRequestId()==0&&t.permitWrites()==0&&t.moves()==0&&t.getSharesByPooledEth(100)==1);}
 function testWrappedRealPermitAndActualReverseAndQuote() public {address user=vm.addr(1);(BatchHarness q,W w,L t)=setup(user,false);WithdrawalQueue.PermitInput memory p=signed(q,w,user);vm.prank(user);uint256[] memory ids=q.requestWithdrawalsWstETHWithPermit(xs(7,8),address(0),p);require(ids[1]==2&&q.metadata(1).cumulativeShares==3&&q.metadata(2).cumulativeShares==7&&q.metadata(2).cumulativeStETH==2300&&w.nonces(user)==1&&w.allowance(user,address(q))==0&&w.totalSupply()==0&&t.moves()==2);}
 function testWrappedLateQuoteRollbackIncludesRealPermit() public {address user=vm.addr(1);(BatchHarness q,W w,L t)=setup(user,true);WithdrawalQueue.PermitInput memory p=signed(q,w,user);vm.prank(user);(bool ok,bytes memory ret)=address(q).call(abi.encodeWithSelector(q.requestWithdrawalsWstETHWithPermit.selector,xs(7,8),address(0),p));require(!ok&&ret.length==0&&q.getLastRequestId()==0&&w.nonces(user)==0&&w.allowance(user,address(q))==0&&w.balanceOf(user)==15&&w.totalSupply()==15&&t.moves()==0);}
}
