[profile.default]
src = "src"
test = "test"
optimizer = true
optimizer_runs = 200
evm_version = "byzantium"
remappings = ["contracts/=vendor/contracts/", "@aragon/os/=vendor/@aragon/os/", "openzeppelin-solidity/=vendor/openzeppelin-solidity/"]
fs_permissions = [{access="read",path="./"}]
