#!/usr/bin/env python3
"""Validate JSON-compatible YAML metadata and render review-only views.

This deliberately does not inspect or parse Lean. Lean remains the theorem
authority; the script only checks and renders declared structured metadata.
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUDIT = ROOT / "audit"
EXPECTED_IDS = [
    "SRV3-LEGACY-ECON",
    "SRV3-ARITH-CHECKED",
    "SRV3-TX-REVERT",
    "SRV3-ALLOC-ORDER",
    "SRV3-MINFIRST-BOUND",
    "SRV3-SOLIDITY-CORR",
    "SRV3-VERITY-431",
    "SRV3-YUL-COMP",
    "SRV3-EVM-RUNTIME",
    "SRV3-SHA256-PRECOMPILE",
    "SRV3-CONSOLIDATION-E2E",
]
EXPECTED_WORDING = [
    "Legacy pure model is not a Solidity or deployed-bytecode correspondence proof.",
    "Quantity bounds and units are model inputs; Solidity correspondence remains unproved.",
    "TxObservation is an abstract transaction model, not an EVM execution trace.",
    "Allocation inputs are source-shaped data, not extracted Solidity state.",
    "The handwritten MinFirst model has no established Solidity/EVM equivalence in M0.",
    "Verity 4.31 is a non-certified development scaffold.",
    "Pinned target is explicitly non-certified and is not used by this Lean 4.24 M0 branch.",
    "Handwritten Yul/direct bytecode must not receive a fabricated Verity projection.",
    "Current consolidation helper uses a Mock build and cannot establish production runtime identity.",
    "SHA-256 precompile hashing currently relies on opaque native FFI.",
    "Mock-derived helper evidence is non-production evidence.",
]
PLANES = {"model", "source", "tx", "yul", "evm", "crypto"}
VIEWS = ("ROADMAP.md", "STATUS.md", "REPRODUCE.md")


def load(name):
    return json.loads((AUDIT / name).read_text(encoding="utf-8"))


def validate():
    registry = load("guarantees.yaml")
    assumptions = load("assumptions.yaml")
    load("exclusions.yaml")
    lock = load("artifacts.lock.json")
    source_map = load("source-map.yaml")
    rows = registry["guarantees"]
    ids = [row["id"] for row in rows]
    assert ids == EXPECTED_IDS, "guarantees must contain the exact ordered minimal-11 IDs"
    assert [row["catalogue_wording"] for row in rows] == EXPECTED_WORDING, \
        "catalogue wording changed"
    assumption_ids = {row["id"] for row in assumptions["assumptions"]}
    for row in rows:
        assert set(row["statuses"]) == PLANES, f"{row['id']}: assurance planes differ"
        assert row["next_gate"], f"{row['id']}: missing next gate"
        assert row["reproduction"]["command"], f"{row['id']}: missing reproduction"
        assert set(row["assumptions"]) <= assumption_ids, f"{row['id']}: unknown assumption"
    assert [row["id"] for row in source_map["targets"]] == EXPECTED_IDS
    for row in source_map["targets"]:
        assert row["status"] == "UNMAPPED" and row["spans"] == []
    assert assumptions["certification"] == {
        "status": "DEV-431-READY",
        "audit_cert": False,
        "statement": "DEV-431-READY is development readiness, not AUDIT-CERT.",
    }
    unavailable = lock["unavailable"]
    assert unavailable
    for name, artifact in unavailable.items():
        assert artifact == {"status": "MISSING", "blocked": True, "value": None}, \
            f"{name}: unavailable provenance must be explicit"
    return rows


def rendered(rows):
    header = (
        "<!-- GENERATED by scripts/audit_metadata.py; edit structured metadata, "
        "not this view. Lean is theorem authority. -->\n\n"
    )
    roadmap = header + "# ROADMAP\n\n" + "\n".join(
        f"- `{row['id']}`: {row['next_gate']}" for row in rows
    ) + "\n"
    status_lines = [
        "# STATUS",
        "",
        "| ID | Model | Source | TX | Yul | EVM | Crypto |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        s = row["statuses"]
        status_lines.append(
            f"| `{row['id']}` | {s['model']} | {s['source']} | {s['tx']} | "
            f"{s['yul']} | {s['evm']} | {s['crypto']} |"
        )
    status = header + "\n".join(status_lines) + "\n"
    reproduce = header + "# REPRODUCE\n\n" + "\n".join(
        f"- `{row['id']}`: `{row['reproduction']['command']}` — "
        f"{row['reproduction']['expected']}"
        for row in rows
    ) + "\n"
    return {"ROADMAP.md": roadmap, "STATUS.md": status, "REPRODUCE.md": reproduce}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("generate", "check"))
    args = parser.parse_args()
    rows = validate()
    views = rendered(rows)
    if args.command == "generate":
        for name, content in views.items():
            (AUDIT / name).write_text(content, encoding="utf-8")
        print("generated audit/ROADMAP.md audit/STATUS.md audit/REPRODUCE.md")
    else:
        for name, content in views.items():
            assert (AUDIT / name).read_text(encoding="utf-8") == content, \
                f"{name} is stale; run scripts/audit_metadata.py generate"
        print("audit metadata ok: exact minimal-11, risks, pins, source-map, generated views")


if __name__ == "__main__":
    main()
